# @package _global_

defaults:
  # - override /controller: egnn
  # - override /noise_schedule: geometric
  - override /energy: hip_energy
  # - override /dataset: t1x_dataset

noise_schedule:
  sigma_min: 1e-3
  sigma_max: 1.0

controller:
  n_atoms: 4 # how many different atoms are in the dataset (one hot encoding)
  hidden_nf: 128
  n_layers: 12

num_epochs: 1000 # 5000
batch_size: 64
# duplicate the same molecule type conditioning in the same batch.
# batch_size should be divisible by duplicates if you want the expected batch_size
# duplicates: 8
num_samples_per_epoch: 128

num_batches_per_epoch: 100

max_score_norm: 150.0
discretization_scheme: ql

num_init_samples: 256 # 1024

num_eval_samples: 128
eval_batch_size: 64

buffer_size: 256 # 1000

amortized: true

# pretraining
pretrain_epochs: 100
# train with adjoint sampling, but populate buffer with T1x structures instead of random or SDE samples
prefill_epochs: 0
scale_bridgematching_loss: True
# if to use only bridge matching for pretraining, or adjoint sampling + bridge matching
BM_only_pretrain: True 
bridgematching_loss_weight: 0.0 # only matters if BM_only_pretrain is False

# min_energy: -25
# max_energy: 25

tau : 5e-3
alpha : 100.0

dataset:
  which: r